name: Windows

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - run: dotnet restore VoiceTraductor.sln
      - run: dotnet build VoiceTraductor.sln --configuration Release --no-restore
      - run: dotnet test VoiceTraductor.sln --configuration Release --no-build
